### ISSUE TITLE
Any news on the site progress? 

### ISSUE THREAD

**Issue by egozi44** [NyaaPantsu/nyaa#1036]
So far most of what I reported still not was fixed.

Using the current site is not that nice experience so far, many things looks unfinished, site have many falls and slowdown times, and uploading torrent when there's no proper options for the uploader such as edit, having proper anonyms feature (and by getting auto log out every 2 minutes while trying to upload the torrent) is Pure nightmare.

Could you please report the to us the progress so far so we could know what the current progress?  

Thanks

**Comment by akuma06** [comment]
We have priorities concerning the issues we are fixing. If your issue hasn't been closed that's because it hasn't been done. That's all. There is no other progress, they will be fixed one day.

Now, even if minor issues are not our top priority, the major ones are fixed or are being fixed. For example, the slowdown times have been greatly decreased and the downtime should be now rare.

I don't see why you are saying that there is no option to edit your torrents, there are if you go on the torrent page and you're logged, there is an edit button.
You do have a proper anonyme feature which is "Mark as Hidden", I know you wanted it to be called something else but it seems it will stay like that for a while.
Please go to dev.pantsu.cat and check that the issues closed were fixed before ;)

**Comment by egozi44** [comment]
Good to know.

I still don't see any edit button though (checked on 3 browsers)
And I also noticed that only on IE I see the date with my OS lang (should be fixed).

The hidden button thingy as I said is confusing, even if you want the anonymous thingy to stay in jap name (which I highly don't recommended) then at least call it "anonymous" in the option cause in any other site Hidden stand as hidden torrent (torrent that only you can see), Nyaa si 
(which lack in many areas and don't seem to give too much thoughts about my suggestions >.>) added it and it really help.

Old nyaa gave us the option to add the torrent as anonymous, hidden (iirc), and the option to delete them entirely, but in the win10 age I guess that most people got used to have less control on their OS ah? xD 
I personally don't like it one bit >.>

**Comment by akuma06** [comment]
If you're checking hidden torrents, there was a bug I think which made the edit button doesn't appear. However it is fixed in dev.

We might think about it for another release, where a "hidden" option might come. However, for now and to not change it without warning other user at the last minute, it will be kept like that. 
You see the date with your OS lang by default if you didn't change the language (or you're blocking cookies) ;).

**Comment by egozi44** [comment]
I also tested Torrent that not was hidden and still don't see edit button so I guess it like that for all types of torrents aside developers. 

I also changed the language, strangely enough in FF and chrome the date being showed in English even when I didn't touch anything xD

**Comment by egozi44** [comment]
oh btw do you also have remember me button in dev mod?
